source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

ruby "~> 2.4.4"
gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', :require => 'bcrypt', platforms: :ruby
gem 'wdm', '>= 0.1.0'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.4'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 4.3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
#i18n & devisei18n
gem 'rails-i18n'
gem 'devise-i18n'
#devise para fazer autenticacao
gem 'devise'
gem 'nokogiri', '~> 1.8.1'
#enum helps
gem 'enum_help'
# Assets / Bootstrap, Jquery etc
source 'https://rails-assets.org' do
gem 'rails-assets-bootstrap', '3.3.7' #
gem 'rails-assets-bootstrap.growl' # BS notify
gem 'rails-assets-animate-css' # animação para BS notify
gem 'rails-assets-bootstrap-markdown' #
gem 'rails-assets-marked' # Markup simples para renderizar HTML
end
gem 'jquery-rails' #
gem 'popper_js' #
gem 'bootstrap_sb_admin_base_v2' # template administrativo
gem "font-awesome-rails" # font
gem 'pundit' #
gem 'money-rails' # coerção de moeda
gem 'paperclip', '~> 5.2.0' # attachment para imagem
gem 'lerolero_generator' # gerador de texto etc.
gem 'friendly_id' # url amigável.
gem 'ratyrate'
gem 'kaminari' # paginate
gem 'kaminari-i18n'
###################################

gem 'coffee-rails', '~> 4.2'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'better_errors'
  gem 'rails-erd'
  gem 'faker'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
